from math import pi
from Utils.General import eps

# World dimensions
WIDTH = 400
HEIGHT = 700
SIDEWALK_WIDTH = 21.5
MIDDLE_LEFT = (WIDTH / 2 + SIDEWALK_WIDTH) / 2
MIDDLE_RIGHT = WIDTH - MIDDLE_LEFT 

#  Sample time parameters
FREQUENCY = 60.0
SAMPLE_TIME = 1.0 / FREQUENCY

# Sprite locations
BACKGROUND_SPRITE = "Sprites/background.png"
CAR_SPRITE = "Sprites/car.png"

# Car parameters
CAR_WIDTH = 90
CAR_HEIGHT = 150
CAR_START_LEFT = (MIDDLE_LEFT, HEIGHT/2 - CAR_HEIGHT)
CAR_START_RIGHT = (MIDDLE_RIGHT, HEIGHT/2 - CAR_HEIGHT)
CAR_ACCELERATION = 0.2
CAR_ANGLE_STEP = pi / 200
CAR_MAX_SPEED = 20
MAX_STEERING_WHEEL_ANGLE = pi / 10
INERTIA_PARAMETER_WHEEL = CAR_ANGLE_STEP/3
INERTIA_PARAMETER_SPEED = CAR_ACCELERATION/10

# RGB colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
