from math import pi
from Utils.General import eps

# World dimensions
WIDTH = 400
HEIGHT = 700
SIDEWALK_WIDTH = 21.5
MIDDLE_LEFT = (WIDTH / 2 + SIDEWALK_WIDTH) / 2
MIDDLE_RIGHT = WIDTH - MIDDLE_LEFT 

#  Sample time parameters
FREQUENCY = 180.0
SAMPLE_TIME = 1.0 / FREQUENCY

# Sprite locations
BACKGROUND_SPRITE = "Sprites/background.png"
CAR_SPRITE = "Sprites/car.png"

# Car parameters
CAR_WIDTH = 45
CAR_HEIGHT = 75
CAR_MASS = 1000
CAR_START_LEFT = (MIDDLE_LEFT, HEIGHT/2 - CAR_HEIGHT)
CAR_START_RIGHT = (MIDDLE_RIGHT, HEIGHT/2 - CAR_HEIGHT)
CAR_ACCELERATION = 12*60
CAR_ANGLE_STEP = pi / 200
CAR_MAX_SPEED = 1200
MAX_STEERING_WHEEL_ANGLE = 5*pi / 180
INERTIA_PARAMETER_WHEEL = CAR_ANGLE_STEP/2
WIND_B = 100
MAX_F_COMMAND = 1000*12*60

# RGB colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
